<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- 项目基本信息 -->
    <groupId>lzt.mybatis</groupId>
    <artifactId>my_mybatis-12-generator</artifactId>
    <version>1.0-SNAPSHOT</version>

    <!-- 构建配置 -->
    <build>
        <plugins>
            <!-- MyBatis Generator 插件配置 -->
            <plugin>
                <groupId>org.mybatis.generator</groupId>
                <artifactId>mybatis-generator-maven-plugin</artifactId>
                <version>1.4.1</version>
                <configuration>
                    <!-- 允许覆盖已存在的文件 -->
                    <overwrite>true</overwrite>
                </configuration>
                <dependencies>
                    <!-- 添加MySQL驱动依赖，使插件能连接数据库 -->
                    <dependency>
                        <groupId>com.mysql</groupId>
                        <artifactId>mysql-connector-j</artifactId>
                        <version>8.4.0</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
</project>